services:
  active_learning_ner:
    container_name: active_learning_ner
    image: heartexlabs/label-studio-ml-backend:active-learning-ner
    init: true
    restart: always
    build:
      context: ../../..
      dockerfile: label_studio_ml/examples/active_learning_ner/Dockerfile
    command: >
      bash -c "
        export PYTHONPATH=/app:$PYTHONPATH &&
        python /app/label_studio_ml/examples/active_learning_ner/run_server.py
      "
    env_file:
      - .env
    environment:
      - LABEL_STUDIO_URL=http://localhost:17777
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
      - DEBUG=1
      - FLASK_APP=/app/label_studio_ml/examples/active_learning_ner/run_server.py
      - FLASK_ENV=development
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      - "./data/.cache:/root/.cache"
      - "./data/mlruns:/app/mlruns"
    network_mode: "host"
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
    # networks:
      # - label-studio-network

# networks:
  # label-studio-network:
    # driver: bridge 